### ISSUE TITLE
Climate Library is generating more climate data than necessary

### ISSUE THREAD

**Issue by mslucash** [LANDIS-II-Foundation/Library-Climate#1]
When run in DailySequenced (and perhaps in other formats), the climate library generates about 2X the number of years of data than Century really needs for spin-up.   Either the calc of the oldest cohort is not correct or the code within the climate library to generate the years of climate has an error.  Brian M. found the bug on 2/28/16.

**Comment by rmscheller** [comment]
Melissa, is this still an issue?

**Comment by mslucash** [comment]
It's still an issue in the publicly available NECN but it's not a problem, just slows it down a tiny bit.  It's not an issue in the new NECN_Hydro..  Recommend closing the issue.
