### ISSUE TITLE
using FireClimate should be optional

### ISSUE THREAD

**Issue by mslucash** [LANDIS-II-Foundation/Library-Climate#12]
Could you convert UsingFireClimate to be optional in the climate input txt file?  Or if you want it to be there ,add it as an explicit error message.  Right now it just triggers a stack trace which isn't easily traceable based on the error message. @rmscheller

**Comment by rmscheller** [comment]
Actually, it is ReadOptionalVar - and so I'm not sure why it struggles.  See: https://github.com/LANDIS-II-Foundation/Library-Climate/blob/master/src/Utility/InputParameterParser.cs
line 114
