### ISSUE TITLE
FileVersion is incorrect

### ISSUE THREAD

**Issue by rmscheller** [LANDIS-II-Foundation/Library-Climate#16]
The fileversion property in the *.csproj file should be 4.0, not 7.0.

**Comment by rmscheller** [comment]
The versions should now be 4.1:  https://github.com/LANDIS-II-Foundation/Library-Climate/blob/master/src/climate-generator.csproj

The installer won't replace it if the version is the same.

**Comment by mslucash** [comment]
OK, see if that works @rmscheller

**Comment by rmscheller** [comment]
Is the dll in deploy sub-folder correct?  The date (May 1) precedes the issue date (May 5).

**Comment by mslucash** [comment]
Now it is correct. I made some more code changes to 4.1 and updated the docs, but I figured that was fine because it wasn't released anyway. Ready to be incorporated into NECN if you want.
