### ISSUE TITLE
monthly PET calculated correctly?

### ISSUE THREAD

**Issue by rmscheller** [LANDIS-II-Foundation/Library-Climate#18]
From a user:

I am wondering the latest climate library may have a bug in the calculation of PET when monthly climate data is used.

I checked water dynamics using the debug mode of Visual Studio and found that PET is NaN in SoilWater.cs.
These errors only occur when I use monthly climate data. If I use daily climate data, these errors disappeared.

**Comment by mslucash** [comment]
There was an error in monthly temp, which occurred when I added average temp as a potential input variable. Code has been fixed and it works now for me.

**Comment by rmscheller** [comment]
I copied into the Support-Library-v7 repo.
