### ISSUE TITLE
Directly add PET as a climate variable

### ISSUE THREAD

**Issue by paulhenne** [LANDIS-II-Foundation/Library-Climate#19]
Would it be feasible directly add PET as a variable to the climate library and bypass the internal calculation of PET?  This addition would allow input of externally-calculated PET using other approaches (e.g., Penman-Monteith) that may provide a more realistic approximation of PET in a warming climate.  One benefit of this approach is that Penman AET is readily available for CONUS for both historical period (http://www.climatologylab.org/gridmet.html) and from GCMs (http://www.climatologylab.org/maca.html).

**Comment by mslucash** [comment]
yes, I could do that. Why don't you email me directly with your timeframe?

**Comment by mslucash** [comment]
Code modifications have been completed.
