### ISSUE TITLE
Citation for the equation in FireClimate.cs

### ISSUE THREAD

**Issue by ZacharyRobbins** [LANDIS-II-Foundation/Library-Climate#20]
Hello, 
I was wondering where the equation set for FireClimate.cs is from. I do not see it in the documentation or in the src. Could it be added? 

Thanks

**Comment by mslucash** [comment]
That set of code was written by Alec and @rmscheller, not me. Maybe they could provide documentation?

**Comment by rmscheller** [comment]
Actually, it was Louise Loudermilk who wrote the original R code, based off of the Canadian Fire Prediction System.  Our intern, Amin, imported into FireClimate.cs.

**Comment by mslucash** [comment]
@ZacharyRobbins are you OK if I close this issue?

**Comment by ZacharyRobbins** [comment]
I guess, I still think it should have a citation or some source material. But if we've decided that's not possible then yes.  Could be derived from 

Wotton, B. M., Alexander, M. E., & Taylor, S. W. (2009). Updates and revisions to the 1992 Canadian forest fire behavior prediction system. Great Lakes Forestry Centre.
or
Van Wagner, C. E. (1974). Structure of the Canadian forest fire weather index (Vol. 1333). Ontario: Environment Canada, Forestry Service.

**Comment by mslucash** [comment]
@ZacharyRobbins do you want to email Louise? Or want me to email her?

**Comment by ZacharyRobbins** [comment]
@mslucash  I will email her.

**Comment by ZacharyRobbins** [comment]
Louise got it from dynamic fire, which got it from CFPS, based on Van Wagner citation now included in pull request.
