### ISSUE TITLE
Documentation doesn't reference FineFuelMoistureCode, DuffMoistureCode, DroughtCode

### ISSUE THREAD

**Issue by rmscheller** [LANDIS-II-Foundation/Library-Climate#21]
These new variables are undocumented.  What are reasonable starting values?  How would we estimate them?  

Thanks!

Rob

**Comment by mslucash** [comment]
I forgot to update the manual. Done. I just pulled those variables that were hard coded in FireClimate code to make them as optional input parameters.

**Comment by rmscheller** [comment]
Thanks.  Check the PDF... I don't think it converted correctly.
