### ISSUE TITLE
Min and Max Rh: Any effect?

### ISSUE THREAD

**Issue by rmscheller** [LANDIS-II-Foundation/Library-Climate#23]
Note: the FWI is the same whether you reverse the maximum and minimum relative humidity or not.  Is this expected behavior?

**Comment by mslucash** [comment]
Yes, we just use mean Rh

**Comment by mslucash** [comment]
I think FWI just uses the mean Rh, but I'll look at the code later this week

**Comment by mslucash** [comment]
Just uses the mean.
