### ISSUE TITLE
Begin growing season is not being calculated properly.

### ISSUE THREAD

**Issue by mslucash** [LANDIS-II-Foundation/Library-Climate#4]
Algorithm called "CalculateBeginGrowingSeason" returns zero in some years when it shouldn't be.  Note that it doesn't have a measurable impact on p-est, however.

**Comment by rmscheller** [comment]
Is this still an issue?  Are there specific circumstances?

**Comment by mslucash** [comment]
Hmm.  I assume so.  I'll revisit it this week.
