### ISSUE TITLE
Need to merge FWI branch into master

### ISSUE THREAD

**Issue by rmscheller** [LANDIS-II-Foundation/Library-Climate#9]
Vincent's revisions captured in the FWI branch allow daily calculations of FireWeatherIndex.  We need a plan to merge with master.

**Comment by mslucash** [comment]
I'm already using the new FWI branch with this latest installer, correct?  Seems to work fine. Is it just a matter of merging?

**Comment by rmscheller** [comment]
Correct.

**Comment by mslucash** [comment]
But I think you have to do it.  I don't have admin rights on the climate library repo.

**Comment by rmscheller** [comment]
Merged.
